### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by kmturley** [DamRsn/VocoderProject#1]
Thanks for the amazing work.

It is common practice to add a LICENSE file to your repo, to make clear you intentions regarding the code.

There is a handy guide here it should take just a couple of minutes to add:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Thank-you!

**Comment by DamRsn** [comment]
Thanks for the suggestion! I've added a GPLv3 license to the repo.
